spring:
  cloud:
    function:
      definition: fooToBar;fooToBarMsg;negate
    #      definition: fooToBarMsg
    stream:
      bindings:
        fooToBar-in-0:
          destination: foo-stream-a
          binder: sample
        fooToBar-out-0:
          destination: bar-stream-a
          binder: sample
        fooToBarMsg-in-0:
          destination: foo-stream-b
          binder: sample
        fooToBarMsg-out-0:
          destination: bar-stream-b
          binder: sample
        negate-in-0:
          destination: integer-stream-in
          binder: sample
        negate-out-0:
          destination: integer-stream-out
          binder: sample
management:
  endpoints:
    web:
      exposure:
        include:
          - bindings
