spring:
  cloud:
    function:
      definition: fooToBar;negate
    stream:
      bindings:
        fooToBar-in-0:
          destination: foo-stream-a
          binder: sample
        fooToBar-out-0:
          destination: bar-stream-a
          binder: sample
        negate-in-0:
          destination: foo-stream-b
          binder: sample
        negate-out-0:
          destination: bar-stream-b
          binder: sample
management:
  endpoints:
    web:
      exposure:
        include:
          - bindings
